"""Assemble the final translated project repository."""
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List
from utils.logger import logger


def assemble_project(
    output_dir: str,
    requirements_content: str,
    metadata: Dict[str, Any],
    graph_png_path: str = None,
) -> str:
    """
    Assemble the final translated_repo with all artifacts.
    Returns path to the ZIP file.
    """
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    # Write requirements.txt
    (output / "requirements.txt").write_text(requirements_content)
    logger.info("Wrote requirements.txt")

    # Write metadata.json
    (output / "metadata.json").write_text(json.dumps(metadata, indent=2))
    logger.info("Wrote metadata.json")

    # Generate report.md
    report = _generate_report(metadata)
    (output / "report.md").write_text(report)
    logger.info("Wrote report.md")

    # Copy graph PNG if available and not already in the output dir
    if graph_png_path and Path(graph_png_path).exists():
        dest = output / "call_graph.png"
        if Path(graph_png_path).resolve() != dest.resolve():
            shutil.copy2(graph_png_path, dest)

    # Create ZIP
    zip_path = str(output.parent / "translated_repo")
    shutil.make_archive(zip_path, "zip", str(output))
    logger.info(f"Created ZIP: {zip_path}.zip")

    return f"{zip_path}.zip"


def _generate_report(metadata: Dict[str, Any]) -> str:
    """Generate a markdown report summarizing the translation run."""
    errors = metadata.get("errors", [])
    error_section = ""
    if errors:
        error_items = "\n".join(f"- **{e.get('function', 'unknown')}**: {e.get('error', 'unknown')}" for e in errors[:20])
        error_section = f"""
## Errors

{error_items}
"""

    requirements = metadata.get("requirements_generated", [])
    req_section = ""
    if requirements:
        req_section = f"""
## Generated Dependencies

{', '.join(requirements)}
"""

    return f"""# Legacy Code Modernization Report

## Summary

| Metric | Value |
|--------|-------|
| Repository | {metadata.get('repo', 'uploaded files')} |
| Source Language | {metadata.get('source', 'unknown')} |
| Target Language | {metadata.get('target', 'python')} |
| Start Time | {metadata.get('start_time', 'N/A')} |
| End Time | {metadata.get('end_time', 'N/A')} |
| Total Functions | {metadata.get('total_functions', 0)} |
| Successfully Translated | {metadata.get('translated_count', 0)} |
| Compilation Status | {metadata.get('compile_status', 'unknown')} |
| LLM Provider | {metadata.get('llm_provider_used', 'unknown')} |
{req_section}
{error_section}

## Notes

- Functions were translated in **dependency order** (leaf functions first)
- Comment filtering (Context Optimization) was applied to reduce hallucinations
- Compilation was validated using `py_compile`
- Any unresolved items are marked with TODO comments in the code

---
*Generated by Legacy Code Modernizer*
"""
